/**
 * Autogenerated by Thrift Compiler (0.9.1-LINE)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.linecorp.armeria.common.thrift.text;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum Letter implements org.apache.thrift.TEnum {
  ALPHA(1),
  BETA(2),
  CHARLIE(3),
  DELTA(4),
  ECHO(5);

  private final int value;

  private Letter(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Letter findByValue(int value) { 
    switch (value) {
      case 1:
        return ALPHA;
      case 2:
        return BETA;
      case 3:
        return CHARLIE;
      case 4:
        return DELTA;
      case 5:
        return ECHO;
      default:
        return null;
    }
  }
}
