/**
 * Autogenerated by Thrift Compiler (0.9.1-LINE)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.linecorp.armeria.common.thrift.text;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class RpcDebugService {

  public interface Iface {

    public Response doDebug(String methodArg1, long methodArg2, RequestDetails details) throws DebugException, org.apache.thrift.TException;

  }

  public interface AsyncIface {

    public void doDebug(String methodArg1, long methodArg2, RequestDetails details, org.apache.thrift.async.AsyncMethodCallback resultHandler) throws org.apache.thrift.TException;

  }

  public static class Client extends org.apache.thrift.TServiceClient implements Iface {
    public static class Factory implements org.apache.thrift.TServiceClientFactory<Client> {
      public Factory() {}
      public Client getClient(org.apache.thrift.protocol.TProtocol prot) {
        return new Client(prot);
      }
      public Client getClient(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
        return new Client(iprot, oprot);
      }
    }

    public Client(org.apache.thrift.protocol.TProtocol prot)
    {
      super(prot, prot);
    }

    public Client(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
      super(iprot, oprot);
    }

    public Response doDebug(String methodArg1, long methodArg2, RequestDetails details) throws DebugException, org.apache.thrift.TException
    {
      send_doDebug(methodArg1, methodArg2, details);
      return recv_doDebug();
    }

    public void send_doDebug(String methodArg1, long methodArg2, RequestDetails details) throws org.apache.thrift.TException
    {
      doDebug_args args = new doDebug_args();
      args.setMethodArg1(methodArg1);
      args.setMethodArg2(methodArg2);
      args.setDetails(details);
      sendBase("doDebug", args);
    }

    public Response recv_doDebug() throws DebugException, org.apache.thrift.TException
    {
      doDebug_result result = new doDebug_result();
      receiveBase(result, "doDebug");
      if (result.isSetSuccess()) {
        return result.success;
      }
      if (result.e != null) {
        throw result.e;
      }
      throw new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.MISSING_RESULT, "doDebug failed: unknown result");
    }

  }
  public static class AsyncClient extends org.apache.thrift.async.TAsyncClient implements AsyncIface {
    public static class Factory implements org.apache.thrift.async.TAsyncClientFactory<AsyncClient> {
      private org.apache.thrift.async.TAsyncClientManager clientManager;
      private org.apache.thrift.protocol.TProtocolFactory protocolFactory;
      public Factory(org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.protocol.TProtocolFactory protocolFactory) {
        this.clientManager = clientManager;
        this.protocolFactory = protocolFactory;
      }
      public AsyncClient getAsyncClient(org.apache.thrift.transport.TNonblockingTransport transport) {
        return new AsyncClient(protocolFactory, clientManager, transport);
      }
    }

    public AsyncClient(org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.transport.TNonblockingTransport transport) {
      super(protocolFactory, clientManager, transport);
    }

    public void doDebug(String methodArg1, long methodArg2, RequestDetails details, org.apache.thrift.async.AsyncMethodCallback resultHandler) throws org.apache.thrift.TException {
      checkReady();
      doDebug_call method_call = new doDebug_call(methodArg1, methodArg2, details, resultHandler, this, ___protocolFactory, ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class doDebug_call extends org.apache.thrift.async.TAsyncMethodCall {
      private String methodArg1;
      private long methodArg2;
      private RequestDetails details;
      public doDebug_call(String methodArg1, long methodArg2, RequestDetails details, org.apache.thrift.async.AsyncMethodCallback resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws org.apache.thrift.TException {
        super(client, protocolFactory, transport, resultHandler, false);
        this.methodArg1 = methodArg1;
        this.methodArg2 = methodArg2;
        this.details = details;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws org.apache.thrift.TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("doDebug", org.apache.thrift.protocol.TMessageType.CALL, 0));
        doDebug_args args = new doDebug_args();
        args.setMethodArg1(methodArg1);
        args.setMethodArg2(methodArg2);
        args.setDetails(details);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public Response getResult() throws DebugException, org.apache.thrift.TException {
        if (getState() != org.apache.thrift.async.TAsyncMethodCall.State.RESPONSE_READ) {
          throw new IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
        return (new Client(prot)).recv_doDebug();
      }
    }

  }

  public static class Processor<I extends Iface> extends org.apache.thrift.TBaseProcessor<I> implements org.apache.thrift.TProcessor {
    private static final Logger LOGGER = LoggerFactory.getLogger(Processor.class.getName());
    public Processor(I iface) {
      super(iface, getProcessMap(new HashMap<String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>>()));
    }

    protected Processor(I iface, Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends Iface> Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> getProcessMap(Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      processMap.put("doDebug", new doDebug());
      return processMap;
    }

    public static class doDebug<I extends Iface> extends org.apache.thrift.ProcessFunction<I, doDebug_args> {
      public doDebug() {
        super("doDebug");
      }

      public doDebug_args getEmptyArgsInstance() {
        return new doDebug_args();
      }

      protected boolean isOneway() {
        return false;
      }

      public doDebug_result getResult(I iface, doDebug_args args) throws org.apache.thrift.TException {
        doDebug_result result = new doDebug_result();
        try {
          result.success = iface.doDebug(args.methodArg1, args.methodArg2, args.details);
        } catch (DebugException e) {
          result.e = e;
        }
        return result;
      }
    }

  }

  public static class AsyncProcessor<I extends AsyncIface> extends org.apache.thrift.TBaseAsyncProcessor<I> {
    private static final Logger LOGGER = LoggerFactory.getLogger(AsyncProcessor.class.getName());
    public AsyncProcessor(I iface) {
      super(iface, getProcessMap(new HashMap<String, org.apache.thrift.AsyncProcessFunction<I, ? extends org.apache.thrift.TBase, ?>>()));
    }

    protected AsyncProcessor(I iface, Map<String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends AsyncIface> Map<String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase,?>> getProcessMap(Map<String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
      processMap.put("doDebug", new doDebug());
      return processMap;
    }

    public static class doDebug<I extends AsyncIface> extends org.apache.thrift.AsyncProcessFunction<I, doDebug_args, Response> {
      public doDebug() {
        super("doDebug");
      }

      public doDebug_args getEmptyArgsInstance() {
        return new doDebug_args();
      }

      public AsyncMethodCallback<Response> getResultHandler(final AsyncFrameBuffer fb, final int seqid) {
        final org.apache.thrift.AsyncProcessFunction fcall = this;
        return new AsyncMethodCallback<Response>() { 
          public void onComplete(Response o) {
            doDebug_result result = new doDebug_result();
            result.success = o;
            try {
              fcall.sendResponse(fb,result, org.apache.thrift.protocol.TMessageType.REPLY,seqid);
              return;
            } catch (Exception e) {
              LOGGER.error("Exception writing to internal frame buffer", e);
            }
            fb.close();
          }
          public void onError(Exception e) {
            byte msgType = org.apache.thrift.protocol.TMessageType.REPLY;
            org.apache.thrift.TBase msg;
            doDebug_result result = new doDebug_result();
            if (e instanceof DebugException) {
                        result.e = (DebugException) e;
                        result.setEIsSet(true);
                        msg = result;
            }
             else 
            {
              msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
              msg = (org.apache.thrift.TBase)new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.INTERNAL_ERROR, e.getMessage());
            }
            try {
              fcall.sendResponse(fb,msg,msgType,seqid);
              return;
            } catch (Exception ex) {
              LOGGER.error("Exception writing to internal frame buffer", ex);
            }
            fb.close();
          }
        };
      }

      protected boolean isOneway() {
        return false;
      }

      public void start(I iface, doDebug_args args, org.apache.thrift.async.AsyncMethodCallback<Response> resultHandler) throws TException {
        iface.doDebug(args.methodArg1, args.methodArg2, args.details,resultHandler);
      }
    }

  }

  public static class doDebug_args implements org.apache.thrift.TBase<doDebug_args, doDebug_args._Fields>, java.io.Serializable, Cloneable, Comparable<doDebug_args>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("doDebug_args");

    private static final org.apache.thrift.protocol.TField METHOD_ARG1_FIELD_DESC = new org.apache.thrift.protocol.TField("methodArg1", org.apache.thrift.protocol.TType.STRING, (short)1);
    private static final org.apache.thrift.protocol.TField METHOD_ARG2_FIELD_DESC = new org.apache.thrift.protocol.TField("methodArg2", org.apache.thrift.protocol.TType.I64, (short)2);
    private static final org.apache.thrift.protocol.TField DETAILS_FIELD_DESC = new org.apache.thrift.protocol.TField("details", org.apache.thrift.protocol.TType.STRUCT, (short)3);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new doDebug_argsStandardSchemeFactory());
      schemes.put(TupleScheme.class, new doDebug_argsTupleSchemeFactory());
    }

    public String methodArg1; // required
    public long methodArg2; // required
    public RequestDetails details; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      METHOD_ARG1((short)1, "methodArg1"),
      METHOD_ARG2((short)2, "methodArg2"),
      DETAILS((short)3, "details");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // METHOD_ARG1
            return METHOD_ARG1;
          case 2: // METHOD_ARG2
            return METHOD_ARG2;
          case 3: // DETAILS
            return DETAILS;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    private static final int __METHODARG2_ISSET_ID = 0;
    private byte __isset_bitfield = 0;
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.METHOD_ARG1, new org.apache.thrift.meta_data.FieldMetaData("methodArg1", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
      tmpMap.put(_Fields.METHOD_ARG2, new org.apache.thrift.meta_data.FieldMetaData("methodArg2", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
      tmpMap.put(_Fields.DETAILS, new org.apache.thrift.meta_data.FieldMetaData("details", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, RequestDetails.class)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(doDebug_args.class, metaDataMap);
    }

    public doDebug_args() {
    }

    public doDebug_args(
      String methodArg1,
      long methodArg2,
      RequestDetails details)
    {
      this();
      this.methodArg1 = methodArg1;
      this.methodArg2 = methodArg2;
      setMethodArg2IsSet(true);
      this.details = details;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public doDebug_args(doDebug_args other) {
      __isset_bitfield = other.__isset_bitfield;
      if (other.isSetMethodArg1()) {
        this.methodArg1 = other.methodArg1;
      }
      this.methodArg2 = other.methodArg2;
      if (other.isSetDetails()) {
        this.details = new RequestDetails(other.details);
      }
    }

    public doDebug_args deepCopy() {
      return new doDebug_args(this);
    }

    @Override
    public void clear() {
      this.methodArg1 = null;
      setMethodArg2IsSet(false);
      this.methodArg2 = 0;
      this.details = null;
    }

    public String getMethodArg1() {
      return this.methodArg1;
    }

    public doDebug_args setMethodArg1(String methodArg1) {
      this.methodArg1 = methodArg1;
      return this;
    }

    public void unsetMethodArg1() {
      this.methodArg1 = null;
    }

    /** Returns true if field methodArg1 is set (has been assigned a value) and false otherwise */
    public boolean isSetMethodArg1() {
      return this.methodArg1 != null;
    }

    public void setMethodArg1IsSet(boolean value) {
      if (!value) {
        this.methodArg1 = null;
      }
    }

    public long getMethodArg2() {
      return this.methodArg2;
    }

    public doDebug_args setMethodArg2(long methodArg2) {
      this.methodArg2 = methodArg2;
      setMethodArg2IsSet(true);
      return this;
    }

    public void unsetMethodArg2() {
      __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __METHODARG2_ISSET_ID);
    }

    /** Returns true if field methodArg2 is set (has been assigned a value) and false otherwise */
    public boolean isSetMethodArg2() {
      return EncodingUtils.testBit(__isset_bitfield, __METHODARG2_ISSET_ID);
    }

    public void setMethodArg2IsSet(boolean value) {
      __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __METHODARG2_ISSET_ID, value);
    }

    public RequestDetails getDetails() {
      return this.details;
    }

    public doDebug_args setDetails(RequestDetails details) {
      this.details = details;
      return this;
    }

    public void unsetDetails() {
      this.details = null;
    }

    /** Returns true if field details is set (has been assigned a value) and false otherwise */
    public boolean isSetDetails() {
      return this.details != null;
    }

    public void setDetailsIsSet(boolean value) {
      if (!value) {
        this.details = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case METHOD_ARG1:
        if (value == null) {
          unsetMethodArg1();
        } else {
          setMethodArg1((String)value);
        }
        break;

      case METHOD_ARG2:
        if (value == null) {
          unsetMethodArg2();
        } else {
          setMethodArg2((Long)value);
        }
        break;

      case DETAILS:
        if (value == null) {
          unsetDetails();
        } else {
          setDetails((RequestDetails)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case METHOD_ARG1:
        return getMethodArg1();

      case METHOD_ARG2:
        return Long.valueOf(getMethodArg2());

      case DETAILS:
        return getDetails();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case METHOD_ARG1:
        return isSetMethodArg1();
      case METHOD_ARG2:
        return isSetMethodArg2();
      case DETAILS:
        return isSetDetails();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof doDebug_args)
        return this.equals((doDebug_args)that);
      return false;
    }

    public boolean equals(doDebug_args that) {
      if (that == null)
        return false;

      boolean this_present_methodArg1 = true && this.isSetMethodArg1();
      boolean that_present_methodArg1 = true && that.isSetMethodArg1();
      if (this_present_methodArg1 || that_present_methodArg1) {
        if (!(this_present_methodArg1 && that_present_methodArg1))
          return false;
        if (!this.methodArg1.equals(that.methodArg1))
          return false;
      }

      boolean this_present_methodArg2 = true;
      boolean that_present_methodArg2 = true;
      if (this_present_methodArg2 || that_present_methodArg2) {
        if (!(this_present_methodArg2 && that_present_methodArg2))
          return false;
        if (this.methodArg2 != that.methodArg2)
          return false;
      }

      boolean this_present_details = true && this.isSetDetails();
      boolean that_present_details = true && that.isSetDetails();
      if (this_present_details || that_present_details) {
        if (!(this_present_details && that_present_details))
          return false;
        if (!this.details.equals(that.details))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      return 0;
    }

    @Override
    public int compareTo(doDebug_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = Boolean.valueOf(isSetMethodArg1()).compareTo(other.isSetMethodArg1());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetMethodArg1()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.methodArg1, other.methodArg1);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = Boolean.valueOf(isSetMethodArg2()).compareTo(other.isSetMethodArg2());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetMethodArg2()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.methodArg2, other.methodArg2);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = Boolean.valueOf(isSetDetails()).compareTo(other.isSetDetails());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetDetails()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.details, other.details);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
    }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("doDebug_args(");
      boolean first = true;

      sb.append("methodArg1:");
      if (this.methodArg1 == null) {
        sb.append("null");
      } else {
        sb.append(this.methodArg1);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("methodArg2:");
      sb.append(this.methodArg2);
      first = false;
      if (!first) sb.append(", ");
      sb.append("details:");
      if (this.details == null) {
        sb.append("null");
      } else {
        sb.append(this.details);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
      if (details != null) {
        details.validate();
      }
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
        __isset_bitfield = 0;
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class doDebug_argsStandardSchemeFactory implements SchemeFactory {
      public doDebug_argsStandardScheme getScheme() {
        return new doDebug_argsStandardScheme();
      }
    }

    private static class doDebug_argsStandardScheme extends StandardScheme<doDebug_args> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, doDebug_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // METHOD_ARG1
              if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                struct.methodArg1 = iprot.readString();
                struct.setMethodArg1IsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 2: // METHOD_ARG2
              if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
                struct.methodArg2 = iprot.readI64();
                struct.setMethodArg2IsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 3: // DETAILS
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.details = new RequestDetails();
                struct.details.read(iprot);
                struct.setDetailsIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, doDebug_args struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.methodArg1 != null) {
          oprot.writeFieldBegin(METHOD_ARG1_FIELD_DESC);
          oprot.writeString(struct.methodArg1);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldBegin(METHOD_ARG2_FIELD_DESC);
        oprot.writeI64(struct.methodArg2);
        oprot.writeFieldEnd();
        if (struct.details != null) {
          oprot.writeFieldBegin(DETAILS_FIELD_DESC);
          struct.details.write(oprot);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class doDebug_argsTupleSchemeFactory implements SchemeFactory {
      public doDebug_argsTupleScheme getScheme() {
        return new doDebug_argsTupleScheme();
      }
    }

    private static class doDebug_argsTupleScheme extends TupleScheme<doDebug_args> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, doDebug_args struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetMethodArg1()) {
          optionals.set(0);
        }
        if (struct.isSetMethodArg2()) {
          optionals.set(1);
        }
        if (struct.isSetDetails()) {
          optionals.set(2);
        }
        oprot.writeBitSet(optionals, 3);
        if (struct.isSetMethodArg1()) {
          oprot.writeString(struct.methodArg1);
        }
        if (struct.isSetMethodArg2()) {
          oprot.writeI64(struct.methodArg2);
        }
        if (struct.isSetDetails()) {
          struct.details.write(oprot);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, doDebug_args struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(3);
        if (incoming.get(0)) {
          struct.methodArg1 = iprot.readString();
          struct.setMethodArg1IsSet(true);
        }
        if (incoming.get(1)) {
          struct.methodArg2 = iprot.readI64();
          struct.setMethodArg2IsSet(true);
        }
        if (incoming.get(2)) {
          struct.details = new RequestDetails();
          struct.details.read(iprot);
          struct.setDetailsIsSet(true);
        }
      }
    }

  }

  public static class doDebug_result implements org.apache.thrift.TBase<doDebug_result, doDebug_result._Fields>, java.io.Serializable, Cloneable, Comparable<doDebug_result>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("doDebug_result");

    private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("success", org.apache.thrift.protocol.TType.STRUCT, (short)0);
    private static final org.apache.thrift.protocol.TField E_FIELD_DESC = new org.apache.thrift.protocol.TField("e", org.apache.thrift.protocol.TType.STRUCT, (short)1);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new doDebug_resultStandardSchemeFactory());
      schemes.put(TupleScheme.class, new doDebug_resultTupleSchemeFactory());
    }

    public Response success; // required
    public DebugException e; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      SUCCESS((short)0, "success"),
      E((short)1, "e");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 0: // SUCCESS
            return SUCCESS;
          case 1: // E
            return E;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("success", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Response.class)));
      tmpMap.put(_Fields.E, new org.apache.thrift.meta_data.FieldMetaData("e", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(doDebug_result.class, metaDataMap);
    }

    public doDebug_result() {
    }

    public doDebug_result(
      Response success,
      DebugException e)
    {
      this();
      this.success = success;
      this.e = e;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public doDebug_result(doDebug_result other) {
      if (other.isSetSuccess()) {
        this.success = new Response(other.success);
      }
      if (other.isSetE()) {
        this.e = new DebugException(other.e);
      }
    }

    public doDebug_result deepCopy() {
      return new doDebug_result(this);
    }

    @Override
    public void clear() {
      this.success = null;
      this.e = null;
    }

    public Response getSuccess() {
      return this.success;
    }

    public doDebug_result setSuccess(Response success) {
      this.success = success;
      return this;
    }

    public void unsetSuccess() {
      this.success = null;
    }

    /** Returns true if field success is set (has been assigned a value) and false otherwise */
    public boolean isSetSuccess() {
      return this.success != null;
    }

    public void setSuccessIsSet(boolean value) {
      if (!value) {
        this.success = null;
      }
    }

    public DebugException getE() {
      return this.e;
    }

    public doDebug_result setE(DebugException e) {
      this.e = e;
      return this;
    }

    public void unsetE() {
      this.e = null;
    }

    /** Returns true if field e is set (has been assigned a value) and false otherwise */
    public boolean isSetE() {
      return this.e != null;
    }

    public void setEIsSet(boolean value) {
      if (!value) {
        this.e = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case SUCCESS:
        if (value == null) {
          unsetSuccess();
        } else {
          setSuccess((Response)value);
        }
        break;

      case E:
        if (value == null) {
          unsetE();
        } else {
          setE((DebugException)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case SUCCESS:
        return getSuccess();

      case E:
        return getE();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case SUCCESS:
        return isSetSuccess();
      case E:
        return isSetE();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof doDebug_result)
        return this.equals((doDebug_result)that);
      return false;
    }

    public boolean equals(doDebug_result that) {
      if (that == null)
        return false;

      boolean this_present_success = true && this.isSetSuccess();
      boolean that_present_success = true && that.isSetSuccess();
      if (this_present_success || that_present_success) {
        if (!(this_present_success && that_present_success))
          return false;
        if (!this.success.equals(that.success))
          return false;
      }

      boolean this_present_e = true && this.isSetE();
      boolean that_present_e = true && that.isSetE();
      if (this_present_e || that_present_e) {
        if (!(this_present_e && that_present_e))
          return false;
        if (!this.e.equals(that.e))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      return 0;
    }

    @Override
    public int compareTo(doDebug_result other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = Boolean.valueOf(isSetSuccess()).compareTo(other.isSetSuccess());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSuccess()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, other.success);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = Boolean.valueOf(isSetE()).compareTo(other.isSetE());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetE()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.e, other.e);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
      }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("doDebug_result(");
      boolean first = true;

      sb.append("success:");
      if (this.success == null) {
        sb.append("null");
      } else {
        sb.append(this.success);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("e:");
      if (this.e == null) {
        sb.append("null");
      } else {
        sb.append(this.e);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
      if (success != null) {
        success.validate();
      }
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class doDebug_resultStandardSchemeFactory implements SchemeFactory {
      public doDebug_resultStandardScheme getScheme() {
        return new doDebug_resultStandardScheme();
      }
    }

    private static class doDebug_resultStandardScheme extends StandardScheme<doDebug_result> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, doDebug_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 0: // SUCCESS
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.success = new Response();
                struct.success.read(iprot);
                struct.setSuccessIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 1: // E
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.e = new DebugException();
                struct.e.read(iprot);
                struct.setEIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, doDebug_result struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.success != null) {
          oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
          struct.success.write(oprot);
          oprot.writeFieldEnd();
        }
        if (struct.e != null) {
          oprot.writeFieldBegin(E_FIELD_DESC);
          struct.e.write(oprot);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class doDebug_resultTupleSchemeFactory implements SchemeFactory {
      public doDebug_resultTupleScheme getScheme() {
        return new doDebug_resultTupleScheme();
      }
    }

    private static class doDebug_resultTupleScheme extends TupleScheme<doDebug_result> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, doDebug_result struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetSuccess()) {
          optionals.set(0);
        }
        if (struct.isSetE()) {
          optionals.set(1);
        }
        oprot.writeBitSet(optionals, 2);
        if (struct.isSetSuccess()) {
          struct.success.write(oprot);
        }
        if (struct.isSetE()) {
          struct.e.write(oprot);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, doDebug_result struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(2);
        if (incoming.get(0)) {
          struct.success = new Response();
          struct.success.read(iprot);
          struct.setSuccessIsSet(true);
        }
        if (incoming.get(1)) {
          struct.e = new DebugException();
          struct.e.read(iprot);
          struct.setEIsSet(true);
        }
      }
    }

  }

}
