/**
 * Autogenerated by Thrift Compiler (0.9.1-LINE)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.linecorp.armeria.common.thrift.text;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Sub implements org.apache.thrift.TBase<Sub, Sub._Fields>, java.io.Serializable, Cloneable, Comparable<Sub> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Sub");

  private static final org.apache.thrift.protocol.TField S_FIELD_DESC = new org.apache.thrift.protocol.TField("s", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField S2_FIELD_DESC = new org.apache.thrift.protocol.TField("s2", org.apache.thrift.protocol.TType.STRUCT, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new SubStandardSchemeFactory());
    schemes.put(TupleScheme.class, new SubTupleSchemeFactory());
  }

  public int s; // required
  public SubSub s2; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    S((short)1, "s"),
    S2((short)2, "s2");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // S
          return S;
        case 2: // S2
          return S2;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __S_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.S, new org.apache.thrift.meta_data.FieldMetaData("s", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.S2, new org.apache.thrift.meta_data.FieldMetaData("s2", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, SubSub.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Sub.class, metaDataMap);
  }

  public Sub() {
  }

  public Sub(
    int s,
    SubSub s2)
  {
    this();
    this.s = s;
    setSIsSet(true);
    this.s2 = s2;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Sub(Sub other) {
    __isset_bitfield = other.__isset_bitfield;
    this.s = other.s;
    if (other.isSetS2()) {
      this.s2 = new SubSub(other.s2);
    }
  }

  public Sub deepCopy() {
    return new Sub(this);
  }

  @Override
  public void clear() {
    setSIsSet(false);
    this.s = 0;
    this.s2 = null;
  }

  public int getS() {
    return this.s;
  }

  public Sub setS(int s) {
    this.s = s;
    setSIsSet(true);
    return this;
  }

  public void unsetS() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __S_ISSET_ID);
  }

  /** Returns true if field s is set (has been assigned a value) and false otherwise */
  public boolean isSetS() {
    return EncodingUtils.testBit(__isset_bitfield, __S_ISSET_ID);
  }

  public void setSIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __S_ISSET_ID, value);
  }

  public SubSub getS2() {
    return this.s2;
  }

  public Sub setS2(SubSub s2) {
    this.s2 = s2;
    return this;
  }

  public void unsetS2() {
    this.s2 = null;
  }

  /** Returns true if field s2 is set (has been assigned a value) and false otherwise */
  public boolean isSetS2() {
    return this.s2 != null;
  }

  public void setS2IsSet(boolean value) {
    if (!value) {
      this.s2 = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case S:
      if (value == null) {
        unsetS();
      } else {
        setS((Integer)value);
      }
      break;

    case S2:
      if (value == null) {
        unsetS2();
      } else {
        setS2((SubSub)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case S:
      return Integer.valueOf(getS());

    case S2:
      return getS2();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case S:
      return isSetS();
    case S2:
      return isSetS2();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof Sub)
      return this.equals((Sub)that);
    return false;
  }

  public boolean equals(Sub that) {
    if (that == null)
      return false;

    boolean this_present_s = true;
    boolean that_present_s = true;
    if (this_present_s || that_present_s) {
      if (!(this_present_s && that_present_s))
        return false;
      if (this.s != that.s)
        return false;
    }

    boolean this_present_s2 = true && this.isSetS2();
    boolean that_present_s2 = true && that.isSetS2();
    if (this_present_s2 || that_present_s2) {
      if (!(this_present_s2 && that_present_s2))
        return false;
      if (!this.s2.equals(that.s2))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(Sub other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetS()).compareTo(other.isSetS());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetS()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.s, other.s);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetS2()).compareTo(other.isSetS2());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetS2()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.s2, other.s2);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("Sub(");
    boolean first = true;

    sb.append("s:");
    sb.append(this.s);
    first = false;
    if (!first) sb.append(", ");
    sb.append("s2:");
    if (this.s2 == null) {
      sb.append("null");
    } else {
      sb.append(this.s2);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // alas, we cannot check 's' because it's a primitive and you chose the non-beans generator.
    if (s2 == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 's2' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
    if (s2 != null) {
      s2.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SubStandardSchemeFactory implements SchemeFactory {
    public SubStandardScheme getScheme() {
      return new SubStandardScheme();
    }
  }

  private static class SubStandardScheme extends StandardScheme<Sub> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Sub struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // S
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.s = iprot.readI32();
              struct.setSIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // S2
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.s2 = new SubSub();
              struct.s2.read(iprot);
              struct.setS2IsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetS()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 's' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Sub struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(S_FIELD_DESC);
      oprot.writeI32(struct.s);
      oprot.writeFieldEnd();
      if (struct.s2 != null) {
        oprot.writeFieldBegin(S2_FIELD_DESC);
        struct.s2.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SubTupleSchemeFactory implements SchemeFactory {
    public SubTupleScheme getScheme() {
      return new SubTupleScheme();
    }
  }

  private static class SubTupleScheme extends TupleScheme<Sub> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Sub struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeI32(struct.s);
      struct.s2.write(oprot);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Sub struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.s = iprot.readI32();
      struct.setSIsSet(true);
      struct.s2 = new SubSub();
      struct.s2.read(iprot);
      struct.setS2IsSet(true);
    }
  }

}

