version: "{branch}.{build}"

init:
  - git config --global core.autocrlf true

build:
  verbosity: detailed

build_script:
  - gradlew.bat --no-daemon --stacktrace checkstyle build test

cache:
  - "%USERPROFILE%\\.gradle"

environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  GRADLE_OPTS: -Xmx768m

matrix:
  fast_finish: true
