version: "{branch}.{build}"

init:
  - git config --global core.autocrlf true

build:
  verbosity: detailed

build_script:
  - gradlew.bat --no-daemon --stacktrace checkstyle build test

cache:
  - %USERPROFILE%\.gradle

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0

matrix:
  fast_finish: true
