/**
 * Autogenerated by Thrift Compiler (0.9.1-LINE)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.linecorp.armeria.service.test.thrift.main;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum FooEnum implements org.apache.thrift.TEnum {
  VAL1(1),
  VAL2(2),
  VAL3(3);

  private final int value;

  private FooEnum(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static FooEnum findByValue(int value) { 
    switch (value) {
      case 1:
        return VAL1;
      case 2:
        return VAL2;
      case 3:
        return VAL3;
      default:
        return null;
    }
  }
}
