/*
 * Copyright 2018 LINE Corporation
 *
 * LINE Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */
package com.linecorp.armeria.client;

import static java.util.Objects.requireNonNull;

import java.net.InetSocketAddress;

import com.linecorp.armeria.common.SessionProtocol;
import com.linecorp.armeria.common.annotation.UnstableApi;
import com.linecorp.armeria.common.logging.LogLevel;
import com.linecorp.armeria.common.metric.MeterIdPrefix;
import com.linecorp.armeria.common.util.SafeCloseable;
import com.linecorp.armeria.common.util.Ticker;
import com.linecorp.armeria.common.util.Unwrappable;

import io.micrometer.core.instrument.MeterRegistry;
import io.netty.util.AttributeMap;

/**
 * Listens to the client connection pool events.
 */
public interface ConnectionPoolListener extends Unwrappable, SafeCloseable {

    /**
     * Returns an instance that does nothing.
     */
    static ConnectionPoolListener noop() {
        return ConnectionPoolListenerAdapter.NOOP;
    }

    /**
     * Returns a {@link ConnectionPoolListener} that logs the connection pool events.
     */
    static ConnectionPoolListener logging() {
        return logging(LogLevel.INFO, LogLevel.TRACE);
    }

    /**
     * Returns a {@link ConnectionPoolListener} that logs the connection pool events with an alternative
     * {@link Ticker}.
     */
    static ConnectionPoolListener logging(Ticker ticker) {
        return new ConnectionPoolLoggingListener(LogLevel.INFO, LogLevel.TRACE, ticker);
    }

    /**
     * Returns a {@link ConnectionPoolListener} that logs the connection pool events.
     */
    static ConnectionPoolListener logging(LogLevel connectionLogLevel, LogLevel pingLogLevel) {
        return new ConnectionPoolLoggingListener(connectionLogLevel, pingLogLevel, Ticker.systemTicker());
    }

    /**
     * Returns a new {@link ConnectionPoolListener} that collects metrics into the specified
     * {@link MeterRegistry}. The returned listener will generate the following metrics:
     * <table>
     * <caption>metrics that will be generated by this class</caption>
     * <tr>
     *   <th>metric name</th>
     *   <th>description</th>
     * </tr>
     * <tr>
     *   <td>{@code armeria.client.connections#count{state="opened"}}</td>
     *   <td>The number of opened connection.</td>
     * </tr>
     * <tr>
     *   <td>{@code armeria.client.connections#count{state="closed"}}</td>
     *   <td>The number of closed connections.</td>
     * </tr>
     * <tr>
     *   <td>{@code armeria.client.active.connections#value}</td>
     *   <td>The number of active connections.</td>
     * </tr>
     * </table>
     */
    @UnstableApi
    static ConnectionPoolListener metricCollecting(MeterRegistry registry) {
        return metricCollecting(registry, new MeterIdPrefix("armeria.client"));
    }

    /**
     * Returns a new {@link ConnectionPoolListener} that collects metrics into the specified
     * {@link MeterRegistry} using the {@link MeterIdPrefix}.
     * The returned listener will generate the following metrics:
     * <table>
     * <caption>metrics that will be generated by this class</caption>
     * <tr>
     *   <th>metric name</th>
     *   <th>description</th>
     * </tr>
     * <tr>
     *   <td>{@code <name>.connections#count{state="opened"}}</td>
     *   <td>The number of opened connection.</td>
     * </tr>
     * <tr>
     *   <td>{@code <name>.connections#count{state="closed"}}</td>
     *   <td>The number of closed connections.</td>
     * </tr>
     * <tr>
     *   <td>{@code <name>.active.connections#value}</td>
     *   <td>The number of active connections.</td>
     * </tr>
     * </table>
     */
    @UnstableApi
    static ConnectionPoolListener metricCollecting(MeterRegistry registry, MeterIdPrefix meterIdPrefix) {
        return new MetricCollectingConnectionPoolListener(registry, meterIdPrefix);
    }

    /**
     * Invoked when a new connection is open and ready to send a request.
     */
    void connectionOpen(SessionProtocol protocol,
                        InetSocketAddress remoteAddr,
                        InetSocketAddress localAddr,
                        AttributeMap attrs) throws Exception;

    /**
     * Invoked when a connection in the connection pool has been closed.
     * Once a connection has been closed, it is guaranteed
     * that no more events are published for the corresponding connection.
     *
     * @deprecated prefer {@link #connectionClosed(SessionProtocol, InetSocketAddress,
     *             InetSocketAddress, AttributeMap, String)}
     */
    @Deprecated
    void connectionClosed(SessionProtocol protocol,
                          InetSocketAddress remoteAddr,
                          InetSocketAddress localAddr,
                          AttributeMap attrs) throws Exception;

    /**
     * Invoked when a connection in the connection pool has been closed with a hint on
     * why the connection has been closed. Once a connection has been closed, it is guaranteed
     * that no more events are published for the corresponding connection.
     */
    @UnstableApi
    default void connectionClosed(SessionProtocol protocol,
                                  InetSocketAddress remoteAddr,
                                  InetSocketAddress localAddr,
                                  AttributeMap attrs,
                                  String closeHint) throws Exception {
        connectionClosed(protocol, remoteAddr, localAddr, attrs);
    }

    /**
     * Invoked when a ping is written to the peer.
     * For HTTP/1.1, the identifier is an internal request id associated with the ping request.
     * For HTTP/2, the identifier is data as described in the
     * <a href="https://datatracker.ietf.org/doc/html/rfc7540#section-6.7">specification</a>.
     */
    @UnstableApi
    default void onPingSent(SessionProtocol protocol,
                            InetSocketAddress remoteAddr,
                            InetSocketAddress localAddr,
                            AttributeMap attrs,
                            long identifier) throws Exception {}

    /**
     * Invoked when a written ping is acknowledged by the peer.
     * For HTTP/1.1, the identifier is an internal request id associated with the ping request.
     * For HTTP/2, the identifier is data as described in the
     * <a href="https://datatracker.ietf.org/doc/html/rfc7540#section-6.7">specification</a>.
     */
    @UnstableApi
    default void onPingAcknowledged(SessionProtocol protocol,
                                    InetSocketAddress remoteAddr,
                                    InetSocketAddress localAddr,
                                    AttributeMap attrs,
                                    long identifier) throws Exception {}

    @Override
    default ConnectionPoolListener unwrap() {
        return this;
    }

    @Override
    default void close() {
        // Do nothing by default.
    }

    /**
     * Returns a new {@link ConnectionPoolListener} which combines two {@link ConnectionPoolListener}s.
     */
    @UnstableApi
    default ConnectionPoolListener andThen(ConnectionPoolListener nextConnectionPoolListener) {
        requireNonNull(nextConnectionPoolListener, "nextConnectionPoolListener");
        return new ConnectionPoolListener() {
            @Override
            public void connectionOpen(SessionProtocol protocol, InetSocketAddress remoteAddr,
                                       InetSocketAddress localAddr, AttributeMap attrs) throws Exception {
                try {
                    ConnectionPoolListener.this.connectionOpen(protocol, remoteAddr, localAddr, attrs);
                } finally {
                    nextConnectionPoolListener.connectionOpen(protocol, remoteAddr,localAddr,attrs);
                }
            }

            @Override
            public void connectionClosed(SessionProtocol protocol, InetSocketAddress remoteAddr,
                                         InetSocketAddress localAddr, AttributeMap attrs) throws Exception {
                try {
                    ConnectionPoolListener.this.connectionClosed(protocol, remoteAddr, localAddr, attrs);
                } finally {
                    nextConnectionPoolListener.connectionClosed(protocol, remoteAddr,localAddr,attrs);
                }
            }

            @Override
            public void onPingAcknowledged(SessionProtocol protocol, InetSocketAddress remoteAddr,
                                           InetSocketAddress localAddr, AttributeMap attrs, long identifier)
                    throws Exception {
                try {
                    ConnectionPoolListener.this.onPingAcknowledged(protocol, remoteAddr, localAddr, attrs,
                                                                   identifier);
                } finally {
                    nextConnectionPoolListener.onPingAcknowledged(protocol, remoteAddr, localAddr, attrs,
                                                                  identifier);
                }
            }

            @Override
            public void onPingSent(SessionProtocol protocol, InetSocketAddress remoteAddr,
                                   InetSocketAddress localAddr, AttributeMap attrs, long identifier)
                    throws Exception {
                try {
                    ConnectionPoolListener.this.onPingSent(protocol, remoteAddr, localAddr, attrs, identifier);
                } finally {
                    nextConnectionPoolListener.onPingSent(protocol, remoteAddr, localAddr, attrs, identifier);
                }
            }

            @Override
            public void close() {
                try {
                    ConnectionPoolListener.super.close();
                } finally {
                    nextConnectionPoolListener.close();
                }
            }
        };
    }
}
