// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello/service/v1/hello_service.proto

// Protobuf Java Version: 3.25.1
package testing.grpc.jsonname;

public final class HelloServiceOuterClass {
  private HelloServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n$hello/service/v1/hello_service.proto\022\020" +
      "hello.service.v1\032\024hello/v1/hello.proto\032\034" +
      "google/api/annotations.proto2e\n\014HelloSer" +
      "vice\022U\n\005Hello\022\026.hello.v1.HelloRequest\032\024." +
      "hello.v1.HelloReply\"\036\202\323\344\223\002\030\022\026/v1/hello/{" +
      "name_input}B\031\n\025testing.grpc.jsonnameP\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Hello.getDescriptor(),
          com.google.api.AnnotationsProto.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    Hello.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
