// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello/v1/hello.proto

// Protobuf Java Version: 3.25.1
package testing.grpc.jsonname;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hello.v1.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name_input = 1 [json_name = "nameInput"];</code>
   * @return The nameInput.
   */
  String getNameInput();
  /**
   * <code>string name_input = 1 [json_name = "nameInput"];</code>
   * @return The bytes for nameInput.
   */
  com.google.protobuf.ByteString
      getNameInputBytes();
}
