// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello/v1/hello.proto

// Protobuf Java Version: 3.25.1
package testing.grpc.jsonname;

public final class Hello {
  private Hello() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hello_v1_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hello_v1_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hello_v1_HelloReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hello_v1_HelloReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024hello/v1/hello.proto\022\010hello.v1\"-\n\014Hell" +
      "oRequest\022\035\n\nname_input\030\001 \001(\tR\tnameInput\"" +
      "&\n\nHelloReply\022\030\n\007message\030\001 \001(\tR\007messageB" +
      "\031\n\025testing.grpc.jsonnameP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_hello_v1_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_hello_v1_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hello_v1_HelloRequest_descriptor,
        new String[] { "NameInput", });
    internal_static_hello_v1_HelloReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_hello_v1_HelloReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hello_v1_HelloReply_descriptor,
        new String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
