spring.profiles.active: local
# Prevent the embedded Tomcat from opening a TCP/IP port.
server.port: -1
---
spring.profiles: local
armeria:
  ports:
    - port: 0 # Specify the port you want
      protocol: HTTP
