name: 'Component Owners'
on:
  # pull_request_target is suggested for projects where pull requests will be
  # made from forked repositories. If pull_request is used in these cases,
  # the github token will not have sufficient permission to update the PR.
  pull_request_target:

permissions:
  contents: read          # to read changed files
  issues: write           # to read/write issue assignees
  pull-requests: write    # to read/write PR reviewers

jobs:
  run_self:
    runs-on: ubuntu-latest
    name: Auto Assign Owners
    steps:
      - uses: dyladan/component-owners@main
        with:
          config-file: .github/component_owners.yml
          repo-token: ${{ github.token }}
          assign-owners: "false"
          request-owner-reviews: "true"
