name: 'Mark inactive PRs as stale'
on:
  schedule:
    # Update at 10:00 AM UTC+9
    - cron: '0 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-pr-message: 'This PR is stale because it has been open 60 days with no activity.'
          # Mark PRs as stale if they are open and inactive for 60 days.
          days-before-pr-stale: 60
          # Do not mark issues as stale.
          days-before-issue-stale: -1
          # Do not close PRs automatically.
          days-before-close: -1
