name: Publish final artifacts to Maven Central repository

on:
  push:
    tags:
      - armeria-*

env:
  LC_ALL: "en_US.UTF-8"
  DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}

jobs:
  publish:
    name: Publish final artifacts
    if: github.repository == 'line/armeria'
    runs-on: ubicloud-standard-16
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - id: setup-jdk-25
        name: Set up JDK 25
        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
        with:
          distribution: 'zulu'
          java-version: '25'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0

      - name: Build with Gradle
        run: |
          ./gradlew --no-daemon --stacktrace --max-workers=12 --parallel -PflakyTests=false \
          -Pretry=true -PfailOnPassedAfterRetry=false \
          build
        shell: bash

      - name: Publish and close repository
        run: |
          ./gradlew --no-daemon --stacktrace --max-workers=1 publish closeAndReleaseStagingRepository
        env:
          # Should not use '-P' option with 'secrets' that can cause unexpected results
          # if secret values contains white spaces or new lines.
          ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.GPG_KEY_ID }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSWORD }}
        shell: bash

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 18

      - name: Perform post-release process
        working-directory: .github/actions
        run: |
          npm ci
          npm run post-release ${{ github.ref_name }}
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
